import assert from 'node:assert/strict';
import {create} from './rain-route.mjs';
const step=(g,n)=>{for(let i=0;i<n;i++)g.update(1/120)};
let g=create(),cues=0,saves=0,panels=0;
g.a.death=()=>cues++;
g.save=()=>saves++;
const panel=g.panel.bind(g);g.panel=(...args)=>{panels++;panel(...args)};
g.start();g.weave();g.wake=84;g.songs=3;g.score=144;g.bestChain=5;
g.finish('Mind the thorns.');
assert.equal(g.state,4);assert.equal(g.link,null);assert.equal(cues,1);assert.equal(saves,1);assert.equal(panels,0);
g.finish('Duplicate');assert.equal(cues,1);assert.equal(saves,1);
for(const code of['KeyE','Space','KeyD','Enter'])g.handlers.keydown({code,preventDefault(){}});
g.handlers.pointerdown({button:0});g.handlers.pointerup({button:0});
assert.equal(g.state,4);assert(!g.keys.KeyD);assert.equal(g.jumpBuffer,0);
const frozen=[g.wake,g.score,g.songs,g.elapsed,g.storm];
step(g,75);assert.equal(g.state,4);assert.equal(panels,0);
g.handlers.keydown({code:'Escape'});assert.equal(g.state,2);
const stopped=JSON.stringify([g.p,g.time,g.death,g.particles,g.cam]);
step(g,240);assert.equal(JSON.stringify([g.p,g.time,g.death,g.particles,g.cam]),stopped);
g.handlers.pointerdown({button:0});g.handlers.pointerup({button:0});assert.equal(g.state,4);
step(g,120);assert.equal(g.state,4);step(g,34);assert.equal(g.state,3);
assert.deepEqual([g.wake,g.score,g.songs,g.elapsed,g.storm],frozen);
assert.equal(cues,1);assert.equal(saves,1);assert.equal(panels,2);
assert(g.ui.panel.innerHTML.includes('144'));assert(g.ui.panel.innerHTML.includes('Mind the thorns.'));
step(g,300);assert.equal(panels,2);assert(g.particles.length<=100);assert(g.pulses.length<=12);
g.respawn();g.finish('A lost flight.');step(g,30);g.handlers.blur();assert.equal(g.state,2);
g.handlers.keydown({code:'KeyR'});assert.equal(g.state,1);assert.equal(g.death,0);assert.equal(g.resumeState,1);assert.equal(g.p.x,1);assert.equal(g.particles.length,0);
console.log('Death checks passed: delayed results, one-shot audio/save, frozen scoring, ignored stray input, pause/blur continuity and clean restart.');
