import {body,integrate,contacts,tether,anchors,clamp,visible} from './motion.js';
import {Grove,cyan,gold,rainbow} from './grove.js';
import {Character} from './character.js';
import {resetCourse,extend,flowers,hazards} from './course.js';
export class Adventure{
 constructor(r,a,ui){this.r=r;this.a=a;this.ui=ui;this.forest=new Grove(r);this.actor=new Character(r);this.keys={};this.time=0;this.reset();this.state=0;this.bind()}
 reset(){this.a.reset?.();resetCourse();this.p=body(1,.52);this.p.face=1;this.cam=[6,6,Math.max(26,37.7/(this.r.canvas?this.r.canvas.width/this.r.canvas.height:1.78))];this.link=null;this.selected=null;this.state=1;this.death=0;this.resumeState=1;this.elapsed=0;this.chain=0;this.bestChain=0;this.steps=0;this.jumpBuffer=0;this.jumpCut=false;this.wake=0;this.particles=[];this.pulses=[];this.trail=[];this.flowers=flowers;this.songs=0;this.score=0;this.storm=-36;this.keys={};this.lastAnchor=-1;this.cool=0;this.flash=0;this.best=this.best||0;try{this.best=Math.max(this.best,+localStorage.getItem('rainweaver.distance')||0)}catch{}}
 bind(){addEventListener('keydown',e=>{if(e.code==='Tab')return;if(['Space','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='KeyM'){this.a.toggleMute?.();return}if(e.code==='Escape'){if(this.state===2)this.start();else this.pause();return}if(e.code==='KeyR'){this.respawn();return}if(this.state===4)return;if(this.state===2){if(e.code==='Enter'||e.code==='Space')this.start();return}if(this.state===0||this.state===3){this.reset();this.start()}this.keys[e.code]=1;if(e.code==='Space'&&this.state===1)this.jumpBuffer=.12;if(e.code==='KeyE')this.weave()});addEventListener('keyup',e=>{this.keys[e.code]=0;if(e.code==='KeyE'&&!this.keys.Mouse)this.release();if(e.code==='Space'&&this.state===1&&this.jumpCut&&this.p.vy>0){this.p.vy*=.5;this.jumpCut=false}});addEventListener('pointerdown',e=>{if(e.button!==0||this.state===4)return;if(this.state!==1){if(this.state!==2)this.reset();this.start();return}this.keys.Mouse=1;this.weave()});addEventListener('pointerup',e=>{if(e.button!==0)return;let held=this.keys.Mouse;this.keys.Mouse=0;if(held&&!this.keys.KeyE)this.release()});addEventListener('blur',()=>this.pause())}
 panel(title,text,button){this.ui.panel.innerHTML=`<div class="card"><div class="eyebrow">RAINWEAVER · ENDLESS FLIGHT</div><h1>${title}</h1><p>${text}</p><button>${button}</button></div>`;this.ui.panel.classList.remove('hide')}
 start(){this.state=this.state===2?this.resumeState:1;this.ui.panel.classList.add('hide');this.a.unlock?.();this.a.pause?.(false)}
 pause(){if(this.state!==1&&this.state!==4)return;this.resumeState=this.state;this.state=2;this.keys={};this.jumpBuffer=0;this.jumpCut=false;this.a.pause?.(true);this.panel('Stillness','ESC / click to resume.','RESUME')}
 save(){this.best=Math.max(this.best,Math.floor(this.wake));try{localStorage.setItem('rainweaver.distance',this.best)}catch{}}
 respawn(){this.save();this.reset();this.start()}
 finish(reason){if(this.state!==1)return;this.state=4;this.death=0;this.reason=reason;this.link=this.selected=null;this.keys={};this.jumpBuffer=0;this.jumpCut=false;this.p.ground=0;this.p.vx*=.12;this.p.vy=this.p.y<-7?6:clamp(this.p.vy*.08,-1,1);this.save();this.a.death?.();this.burst(this.p.x,this.p.y+.3,gold,28);this.ui.hint.textContent=this.ui.location.textContent=''}
 effects(dt){for(let f of this.pulses)f.life-=dt;this.pulses=this.pulses.filter(f=>f.life>0).slice(-12);for(let f of this.particles){f.life-=dt;f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy-=dt}this.particles=this.particles.filter(f=>f.life>0).slice(-100);this.trail=this.trail.filter(f=>this.time-f.t<.6)}
 candidate(){let p=this.p,best=null,score=-1e9,dir=(this.keys.KeyA||this.keys.ArrowLeft)?-1:1;for(let q of anchors){let dx=q.x-p.x,dy=q.y-p.y,d=Math.hypot(dx,dy);if(q.broken||d>10.2||dy<.6||dy>10||q.id===this.lastAnchor&&this.cool>0||!visible(p,q))continue;let s=6-d*.42+dx*dir*.6+(q===this.selected?.q?1:0);if(s>score){score=s;best=q}}return best}
 weave(){if(this.state!==1||this.link)return;let q=this.candidate();if(!q){this.flash=.12;return}this.link={q,length:Math.max(2.5,Math.hypot(this.p.x-q.x,this.p.y-q.y)),left:q.ttl};this.jumpCut=false;this.chain++;this.bestChain=Math.max(this.bestChain,this.chain);this.a.fixed?.(q.id);this.burst(q.x,q.y,gold,12)}
 release(){if(this.state!==1||!this.link)return;this.lastAnchor=this.link.q.id;this.cool=.3;this.link=null;this.jumpCut=false;this.a.recall?.();this.burst(this.p.x,this.p.y,cyan,6)}
 burst(x,y,c,n,flat=1){this.pulses.push({x,y,c,flat,life:.6});for(let i=0;i<n;i++){let angle=Math.random()*6.283,s=1+Math.random()*4;this.particles.push({x,y,z:Math.random()*.5,vx:Math.cos(angle)*s,vy:Math.sin(angle)*s,life:.5+Math.random()*.5,c})}}
 update(dt){if(this.state===4){this.death+=dt;if(this.death>.12){this.time+=dt*.3;this.p.x+=this.p.vx*dt;this.p.y+=this.p.vy*dt;this.p.vy+=dt*1.8;this.effects(dt*.7);this.cam[0]+=(this.p.x+1-this.cam[0])*dt*2;this.cam[1]+=(this.p.y+3.6-this.cam[1])*dt*2;if(this.death<1.1&&this.particles.length<22)this.burst(this.p.x,this.p.y+.4,cyan,12)}if(this.death>=1.9){this.state=3;this.panel(this.reason,`${Math.floor(this.wake)} m · BEST ${this.best} m<br>SCORE ${this.score} · ${this.songs} dew songs<br>CHAIN ${this.bestChain}`, 'FLY AGAIN')}return}if(this.state!==1){if(this.state===0)this.time+=dt;return}this.time+=dt;this.elapsed+=dt;extend(this.wake);this.cool=Math.max(0,this.cool-dt);this.flash=Math.max(0,this.flash-dt);this.jumpBuffer=Math.max(0,this.jumpBuffer-dt);let p=this.p,d=(this.keys.KeyD||this.keys.ArrowRight?1:0)-(this.keys.KeyA||this.keys.ArrowLeft?1:0),wasGround=p.ground>0;if(d)p.face+=(d-p.face)*Math.min(1,dt*15);
 if(this.link?.q.ttl&&(this.link.left-=dt)<=0){this.link.q.broken=true;this.burst(this.link.q.x,this.link.q.y,rainbow[6],15);this.release()}
 if(this.jumpBuffer>0&&p.ground>0){p.vy=9;p.ground=0;this.jumpBuffer=0;this.jumpCut=!this.link;this.a.jump?.();this.burst(p.x,p.y-.5,cyan,10,.25)}
 if(this.link){let q=this.link.q,dx=p.x-q.x,dy=p.y-q.y,l=Math.hypot(dx,dy)||1,tx=-dy/l,ty=dx/l,force=d*20;p.vx+=tx*force*dt;p.vy+=ty*force*dt;if(this.keys.ShiftLeft||this.keys.ShiftRight)this.link.length=Math.max(2.5,this.link.length-1.8*dt);p.vx*=Math.exp(-.08*dt);p.vy*=Math.exp(-.08*dt)}else if(p.ground>0){p.vx+=(d*7-p.vx)*Math.min(1,dt*12)}else{p.vx+=d*9*dt;p.vx*=Math.exp(-.13*dt)}
 let speed=Math.hypot(p.vx,p.vy);if(speed>18){p.vx*=18/speed;p.vy*=18/speed}integrate(p,dt);if(this.link&&!visible(p,this.link.q))this.release();if(this.link){for(let i=0;i<3;i++){tether(p,this.link.q,this.link.length);contacts(p)}}p.x=Math.max(-4,p.x);
 if(!wasGround&&p.ground>0){this.a.land?.(speed);this.burst(p.x,p.y-.5,cyan,14,.2);this.chain=0}this.wake=Math.max(this.wake,p.x);this.score=Math.floor(this.wake)+this.songs*20;
 if(this.elapsed>5)this.storm=Math.max(this.wake-42,this.storm+Math.min(9,4+this.elapsed*.035)*dt);if(p.x<this.storm){this.finish('Outrun the dark.');return}if(p.y<-7){this.finish('A lost flight.');return}for(let h of hazards){h.y=h.base+Math.sin(this.time*h.speed+h.phase)*h.amp;if(Math.hypot(p.x-h.x,p.y-h.y)<p.r+h.r){this.finish('Mind the thorns.');return}}
 this.selected={q:this.candidate()};for(let f of this.flowers)if(!f.lit&&Math.hypot(p.x-f.x,p.y-f.y)<1.3){f.lit=true;this.songs++;this.score+=20;this.a.flower?.(this.songs);this.burst(f.x,f.y,gold,15)}
 this.steps+=Math.abs(p.vx)*dt;this.effects(dt);if(this.time-(this.trail.at(-1)?.t||-1)>.025)this.trail.push({x:p.x-.35*p.face,y:p.y+.25,z:0,t:this.time});
 let aspect=this.r.canvas?this.r.canvas.width/this.r.canvas.height:1.78;this.cam[2]+=(Math.max(26,26*1.45/aspect)-this.cam[2])*dt*2;this.cam[0]+=(Math.max(6,p.x+3+clamp(p.vx*.12,-1.5,1.5))-this.cam[0])*(1-Math.exp(-dt*4));this.cam[1]+=(Math.max(5.8,p.y+3.6)-this.cam[1])*(1-Math.exp(-dt*3));this.a.update?.(dt,speed,this.chain);
 this.ui.hp.textContent=`${Math.floor(this.wake)} m · BEST ${this.best}`;this.ui.count.textContent=this.score;this.ui.location.textContent=p.x-this.storm<15?'DARKNESS · '+Math.ceil(p.x-this.storm)+' m BEHIND':'SECTOR '+(1+Math.floor(this.wake/112));this.ui.hint.textContent=this.link?.q.ttl?'FRAGILE BRANCH · '+this.link.left.toFixed(1)+' s · RELEASE TO FLY':this.link?'A / D  SWING · RELEASE E / MOUSE TO FLY':p.x<8?'A / D MOVE · SPACE JUMP · HOLD E / MOUSE CATCH':this.selected.q?.ttl?'PINK BRANCH BREAKS · KEEP MOVING':'HOLD E / MOUSE CATCH · AVOID THORNS · R NEW RUN';
 }
 ring(r,x,y,size,c,fade=1,flat=1,fill=1){for(let i=0;i<24*fill;i++){let a=i/24*6.283,b=Math.min(i+1,24*fill)/24*6.283;r.branch([x+Math.cos(a)*size,y+Math.sin(a)*size*flat,.3],[x+Math.cos(b)*size,y+Math.sin(b)*size*flat,.3],.017*fade,c,2)}}
 render(){let r=this.r,p=this.p,light=this.link?.q||this.selected?.q;r.begin(this.cam,[p.x,p.y+.5,0],this.time,this.flash,light?[light.x,light.y,1]:undefined,clamp((this.death-.5)/1.4,0,1));this.forest.draw(r,this.cam[0],this.time,this.wake);for(let q of anchors){if(q.broken||Math.abs(q.x-this.cam[0])>23)continue;let active=q===this.selected?.q||q===this.link?.q,c=q.ttl?rainbow[6]:active?gold:cyan;for(let k=-1;k<=1;k++)r.ball(q.x+k*.18,q.y+.12+Math.abs(k)*.12,0,.13,.25,.12,c,active?1.8:.55,-k*.5);r.branch([q.x,q.y+.15,0],[q.x,q.y+.6,0],.035,c,.2);r.glow(q.x,q.y,.25,active?1.9:.9,active?1.9:.9,c);if(active)this.ring(r,q.x,q.y,.53+Math.sin(this.time*4)*.04,c,1,1,q.ttl&&q===this.link?.q?this.link.left/q.ttl:1)}
 for(let h of hazards)if(Math.abs(h.x-this.cam[0])<24){r.ball(h.x,h.y,0,h.r*.65,h.r*.65,h.r*.65,[.15,.025,.09]);for(let i=0;i<10;i++){let a=i*.628+this.time,b=a+.25;r.branch([h.x+Math.cos(a)*h.r*.4,h.y+Math.sin(a)*h.r*.4,0],[h.x+Math.cos(b)*h.r,h.y+Math.sin(b)*h.r,0],.07,rainbow[0],.8)}}
 if(this.storm>this.cam[0]-28){r.box(this.storm-9,4,1,9,14,.5,[.006,.002,.015]);for(let i=0;i<18;i++){let y=i-5;r.branch([this.storm-1,y,1],[this.storm+Math.sin(this.time*2+i)*.25,y+.8,1],.12,[.32,.045,.2],.5)}}
 for(let f of this.flowers)if(!f.lit&&Math.abs(f.x-this.cam[0])<20){let y=f.y+Math.sin(this.time*2+f.x)*.1;this.ring(r,f.x,y,.23,gold);r.ball(f.x,y,0,.07,.13,.07,gold,2)}
 r.actorFade=clamp((this.death-.22)/1.05,0,1);this.actor.draw(r,p,this.time,this.steps,!!this.link);r.actorFade=0;r.glow(p.x,p.y+.4,.3,1.4,1.6,[.05,.18,.16].map(c=>c*(1-clamp(this.death,0,1))));if(this.link){let h=this.actor.horn(p),q=this.link.q;for(let i=0;i<20;i++){let at=t=>[h[0]+(q.x-h[0])*t,h[1]+(q.y-h[1])*t-Math.sin(t*Math.PI)*.1,0];r.branch(at(i/20),at((i+1)/20),.027,i>15?gold:cyan,2.4)}}
 for(let i=1;i<this.trail.length;i++){let a=this.trail[i-1],b=this.trail[i],s=i/this.trail.length;for(let j=-1;j<=1;j++)r.branch([a.x,a.y+j*.08*s,0],[b.x,b.y+j*.08*s,0],s*(j?.014:.035),j?cyan:[.6,1,.9],1.5*s)}
 for(let f of this.pulses){let s=1-f.life/.6;this.ring(r,f.x,f.y,.15+s*1.8,f.c,(1-s)*.8,f.flat);r.glow(f.x,f.y,.4,2*f.life,2*f.life*f.flat,f.c)}
 for(let f of this.particles){let s=.035*f.life;r.branch([f.x-f.vx*.045,f.y-f.vy*.045,f.z],[f.x,f.y,f.z],s,f.c,3);r.glow(f.x,f.y,f.z,.18*f.life,.18*f.life,f.c)}r.end()}
}
