const VS=`#version 300 es
precision highp float;
layout(location=0)in vec3 a;layout(location=1)in vec3 n;
layout(location=2)in vec4 m0;layout(location=3)in vec4 m1;layout(location=4)in vec4 m2;layout(location=5)in vec4 m3;layout(location=6)in vec4 color;
uniform mat4 vp,light;uniform float time;out vec3 w,N;out vec2 U;out vec4 col,shadow;
void main(){mat4 m=mat4(m0,m1,m2,m3);U=a.xy;w=(m*vec4(a,1)).xyz;if(color.a==-4.)w.xy+=vec2(.1,.04)*sin(time*1.3+w.x*.8+w.z)*length(a);N=normalize(m0.xyz*n.x/dot(m0.xyz,m0.xyz)+m1.xyz*n.y/dot(m1.xyz,m1.xyz)+m2.xyz*n.z/dot(m2.xyz,m2.xyz));col=color;shadow=light*vec4(w,1);gl_Position=vp*vec4(w,1);}`;
const NOISE=`float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);vec3 s=vec3(7.,157.,113.);float n=dot(i,s);vec4 a=fract(sin(n+vec4(0,7,157,164))*43758.54),b=fract(sin(n+113.+vec4(0,7,157,164))*43758.54);return mix(mix(mix(a.x,a.y,f.x),mix(a.z,a.w,f.x),f.y),mix(mix(b.x,b.y,f.x),mix(b.z,b.w,f.x),f.y),f.z);}
float dissolve(){if(col.a>-10.)return 0.;float f=-col.a-10.,d=noise(w*11.);if(f>=1.||d<f)discard;return (1.-smoothstep(0.,.12,d-f))*smoothstep(0.,.15,f);}`;
const FS=`#version 300 es
precision highp float;in vec3 w,N;in vec2 U;in vec4 col,shadow;out vec4 o;
uniform sampler2D depth;uniform vec3 eye,hero,lamp;uniform float time;
${NOISE}
void main(){float edge=dissolve();if(col.a==-6.){float d=dot(U,U);if(d>1.)discard;o=vec4(col.rgb*(exp(-d*18.)*1.4+exp(-d*3.)*.3),.65*(1.-d)*(1.-d));return;}vec3 n=normalize(N),v=normalize(eye-w),l=normalize(vec3(-.6,1.,.8));vec3 sc=shadow.xyz/shadow.w*.5+.5;float sh=0.;for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++)sh+=sc.z-.002<texture(depth,sc.xy+vec2(x,y)/1024.).r?1.:.18;sh/=9.;if(sc.x<0.||sc.x>1.||sc.y<0.||sc.y>1.)sh=1.;float diffuse=max(dot(n,l),0.),rim=pow(1.-max(dot(n,v),0.),3.);vec3 c=col.rgb*(.12+diffuse*.8*sh)+vec3(.02,.095,.13)*rim;
float d=length(w-hero);c+=vec3(.03,.1,.12)*pow(max(dot(n,normalize(l+v)),0.),28.)*sh;
if(col.a==-3.){float grain=noise(w*vec3(9.,.65,9.));c*=.45+grain*.8;c+=vec3(.014,.028,.026)*smoothstep(.48,.54,grain)*rim;}
if(col.a==-4.)c+=col.rgb*pow(max(dot(-n,l),0.),2.)*.7;
if(col.a>0.)c+=col.rgb*col.a;
if(col.a==-1.){float rip=sin(w.x*3.+sin(w.z*2.)+time)*sin(w.z*7.-time*2.);c=vec3(.009,.065,.075)+vec3(.05,.25,.28)*pow(max(0.,rip),10.)/(1.+abs(w.x-eye.x-5.)*.3);c+=vec3(.04,.35,.35)/(1.+length(w.xz-hero.xz)*2.);}
if(col.a==-2.){float grain=noise(w*18.)*.4+noise(w*5.)*.4+noise(w)*.2;c=mix(vec3(.012,.018,.025),vec3(.024,.09,.065),smoothstep(.4,.85,n.y+grain*.2))*(.4+diffuse*.7*sh+grain*.45);c+=vec3(.015,.07,.055)/(1.+d*d*.5);}
if(col.a==-5.)c=vec3(.03,.13,.18)*(.7+.3*sin(w.x*27.+sin(w.y-time*4.)))+vec3(.04,.13,.14)*noise(w*vec3(14.,2.,1.)+vec3(0,time*4.,0));
vec3 fire=lamp-w;c+=col.rgb*vec3(.3,.7,.8)*.7/(1.+d*d*.5)+col.rgb*vec3(2.4,1.1,.25)*max(.1,dot(n,normalize(fire)))/(1.+dot(fire,fire)*.6)+vec3(.3,.8,.7)*edge;
float fog=1.-exp(-max(0.,-w.z)*.045);vec3 haze=mix(vec3(.003,.016,.027),vec3(.018,.085,.105),smoothstep(-4.,20.,w.y));haze*=.65+.35*exp(-abs(w.x-eye.x-8.)*.12);c=mix(c,haze,fog);c+=vec3(.004,.019,.02)*exp(-pow((w.y+4.)*.4,2.))*(1.-exp(-max(0.,eye.z-w.z-15.)*.03));o=vec4(c,1);}`;
const DFS=`#version 300 es
precision highp float;in vec3 w;in vec4 col;out vec4 o;${NOISE}void main(){dissolve();o=vec4(1);}`;
const QVS=`#version 300 es
out vec2 uv;void main(){uv=vec2((gl_VertexID<<1)&2,gl_VertexID&2);gl_Position=vec4(uv*2.-1.,0,1);}`;
const SKY=`#version 300 es
precision highp float;in vec2 uv;out vec4 o;uniform float time;uniform vec2 shift;
void main(){vec2 p=uv-vec2(.69,.88);p.x*=shift.y;float moon=length(p),a=atan(p.x,-p.y)+shift.x;vec3 c=mix(vec3(.003,.01,.025),vec3(.009,.04,.068),uv.y);float ray=pow(max(0.,sin(a*31.+sin(a*7.)*2.+time*.07)),7.)+pow(max(0.,sin(a*17.+1.)),12.);c+=vec3(.021,.058,.063)*ray*exp(-moon*1.8);c+=vec3(.1,.26,.27)*(exp(-moon*7.)+exp(-moon*24.)*.5);c+=vec3(.48,.8,.68)*(1.-smoothstep(.045,.05,moon));o=vec4(c,1);}`;
const BLUR=`#version 300 es
precision highp float;in vec2 uv;out vec4 o;uniform sampler2D tex;uniform vec2 step;uniform float cut;
void main(){vec3 c=texture(tex,uv).rgb*.227027;c+=(texture(tex,uv+step*1.384615).rgb+texture(tex,uv-step*1.384615).rgb)*.316216;c+=(texture(tex,uv+step*3.230769).rgb+texture(tex,uv-step*3.230769).rgb)*.07027;o=vec4(max(c-cut,0.),1);}`;
const POST=`#version 300 es
precision highp float;in vec2 uv;out vec4 o;uniform sampler2D tex,bloom;uniform float hurt,fade;
void main(){vec3 c=texture(tex,uv).rgb+texture(bloom,uv).rgb*.75;c*=1.-(.42+fade*.35)*pow(length((uv-.5)*vec2(1.,.8)),1.5);c=mix(c,vec3(.7,.055,.045),hurt*.2);c=mix(c,vec3(dot(c,vec3(.21,.72,.07))),fade*.3)*(1.-fade*.25);c=(c*(2.51*c+.03))/(c*(2.43*c+.59)+.14);o=vec4(pow(c,vec3(.4545)),1);}`;
const norm=a=>{let l=Math.hypot(...a)||1;return a.map(x=>x/l)},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function look(eye,target){let z=norm(eye.map((v,i)=>v-target[i])),x=norm(cross([0,1,0],z)),y=cross(z,x);return[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]}
function mul(a,b){let c=Array(16).fill(0);for(let j=0;j<4;j++)for(let i=0;i<4;i++)for(let k=0;k<4;k++)c[j*4+i]+=a[k*4+i]*b[j*4+k];return c}
function prog(g,v,f){let p=g.createProgram();for(let [type,src]of[[g.VERTEX_SHADER,v],[g.FRAGMENT_SHADER,f]]){let s=g.createShader(type);g.shaderSource(s,src);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw Error(g.getShaderInfoLog(s));g.attachShader(p,s)}g.linkProgram(p);if(!g.getProgramParameter(p,g.LINK_STATUS))throw Error(g.getProgramInfoLog(p));return p}
function meshData(type){let out=[],emit=(p,n)=>out.push(...p,...n);if(type==3){for(let p of[[-1,-1],[1,-1],[1,1],[-1,-1],[1,1],[-1,1]])emit([...p,0],[0,0,1])}else if(type==0){for(let i=0;i<10;i++)for(let j=0;j<14;j++)for(let [di,dj]of[[0,0],[1,0],[1,1],[0,0],[1,1],[0,1]]){let a=(i+di)/10*Math.PI,b=(j+dj)/14*Math.PI*2,p=[Math.sin(a)*Math.cos(b),Math.cos(a),Math.sin(a)*Math.sin(b)];emit(p,p)}}else if(type==1){for(let j=0;j<10;j++){let a=j/10*6.283,b=(j+1)/10*6.283;for(let [q,y]of[[a,0],[b,0],[b,1],[a,0],[b,1],[a,1]]){let r=1-y*.18;emit([Math.cos(q)*r,y,Math.sin(q)*r],norm([Math.cos(q),.18,Math.sin(q)]))}}}else{for(let axis=0;axis<3;axis++)for(let s of[-1,1])for(let [a,b]of[[-1,-1],[1,-1],[1,1],[-1,-1],[1,1],[-1,1]]){let p=[0,0,0],n=[0,0,0];p[axis]=s;p[(axis+1)%3]=a;p[(axis+2)%3]=b;n[axis]=s;emit(p,n)}}return new Float32Array(out)}
export class Renderer{
 mesh(data){let g=this.g,vao=g.createVertexArray();g.bindVertexArray(vao);let v=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,v);g.bufferData(g.ARRAY_BUFFER,new Float32Array(data),g.STATIC_DRAW);for(let i=0;i<2;i++){g.enableVertexAttribArray(i);g.vertexAttribPointer(i,3,g.FLOAT,false,24,i*12)}let inst=g.createBuffer();g.bindBuffer(g.ARRAY_BUFFER,inst);for(let i=0;i<5;i++){g.enableVertexAttribArray(i+2);g.vertexAttribPointer(i+2,4,g.FLOAT,false,80,i*16);g.vertexAttribDivisor(i+2,1)}return this.meshes.push({vao,inst,count:data.length/6,data:[]})-1}
 loft(points,sides=10,depth=1){let rings=[],out=[],count=(points.length-1)*5;for(let i=0;i<=count;i++){let t=i/count*(points.length-1),k=Math.min(points.length-2,Math.floor(t)),f=t-k,ps=[points[Math.max(0,k-1)],points[k],points[k+1],points[Math.min(points.length-1,k+2)]],c=ps[0].map((_,j)=>.5*((2*ps[1][j])+(-ps[0][j]+ps[2][j])*f+(2*ps[0][j]-5*ps[1][j]+4*ps[2][j]-ps[3][j])*f*f+(-ps[0][j]+3*ps[1][j]-3*ps[2][j]+ps[3][j])*f*f*f));rings.push(c)}for(let i=0;i<count;i++)for(let j=0;j<sides;j++)for(let [di,dj]of[[0,0],[1,0],[1,1],[0,0],[1,1],[0,1]]){let k=i+di,c=rings[k],a=(j+dj)/sides*6.283,tan=norm(rings[Math.min(count,k+1)].slice(0,3).map((v,n)=>v-rings[Math.max(0,k-1)][n])),u=norm(cross([0,0,1],tan)),v=cross(tan,u),n=u.map((x,k)=>x*Math.cos(a)+v[k]*Math.sin(a)/depth),p=c.slice(0,3).map((x,k)=>x+Math.max(.001,c[3])*(u[k]*Math.cos(a)+v[k]*Math.sin(a)*depth));out.push(...p,...norm(n))}return this.mesh(out)}
 constructor(canvas){this.canvas=canvas;const g=this.g=canvas.getContext('webgl2',{alpha:false,antialias:false});if(!g)throw Error('WebGL2 is required');this.hdr=!!g.getExtension('EXT_color_buffer_float');this.program=prog(g,VS,FS);this.shadowProgram=prog(g,VS,DFS);this.sky=prog(g,QVS,SKY);this.blur=prog(g,QVS,BLUR);this.post=prog(g,QVS,POST);this.cache=new Map();this.empty=g.createVertexArray();this.meshes=[];for(let type of[0,1,2,3])this.mesh(meshData(type));this.shadowTex=g.createTexture();g.bindTexture(g.TEXTURE_2D,this.shadowTex);g.texImage2D(g.TEXTURE_2D,0,g.DEPTH_COMPONENT24,1024,1024,0,g.DEPTH_COMPONENT,g.UNSIGNED_INT,null);this.params(g.NEAREST);this.shadowFB=g.createFramebuffer();g.bindFramebuffer(g.FRAMEBUFFER,this.shadowFB);g.framebufferTexture2D(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.TEXTURE_2D,this.shadowTex,0);g.drawBuffers([g.NONE]);g.readBuffer(g.NONE);this.camera=[7,5,21];this.resize();addEventListener('resize',()=>this.resize())}
 params(filter){let g=this.g;g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,filter);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,filter);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE)}
 target(w,h,depth){let g=this.g,tex=g.createTexture();g.bindTexture(g.TEXTURE_2D,tex);g.texImage2D(g.TEXTURE_2D,0,this.hdr?g.RGBA16F:g.RGBA8,w,h,0,g.RGBA,this.hdr?g.HALF_FLOAT:g.UNSIGNED_BYTE,null);this.params(g.LINEAR);let fb=g.createFramebuffer();g.bindFramebuffer(g.FRAMEBUFFER,fb);g.framebufferTexture2D(g.FRAMEBUFFER,g.COLOR_ATTACHMENT0,g.TEXTURE_2D,tex,0);let rb;if(depth){rb=g.createRenderbuffer();g.bindRenderbuffer(g.RENDERBUFFER,rb);g.renderbufferStorage(g.RENDERBUFFER,g.DEPTH_COMPONENT24,w,h);g.framebufferRenderbuffer(g.FRAMEBUFFER,g.DEPTH_ATTACHMENT,g.RENDERBUFFER,rb)}if(g.checkFramebufferStatus(g.FRAMEBUFFER)!=g.FRAMEBUFFER_COMPLETE)throw Error('Render target unavailable');return{tex,fb,rb,w,h}}
 resize(){const g=this.g,ratio=innerWidth/innerHeight;this.canvas.width=Math.min(1600,innerWidth*Math.min(devicePixelRatio||1,1.3))|0;this.canvas.height=(this.canvas.width/ratio)|0;for(let t of[this.scene,...this.blooms||[]])if(t){g.deleteTexture(t.tex);g.deleteFramebuffer(t.fb);if(t.rb)g.deleteRenderbuffer(t.rb)}this.scene=this.target(this.canvas.width,this.canvas.height,true);this.blooms=[this.target(Math.max(1,this.canvas.width>>2),Math.max(1,this.canvas.height>>2)),this.target(Math.max(1,this.canvas.width>>2),Math.max(1,this.canvas.height>>2))]}
 loc(p,n){let c=this.cache.get(p);if(!c)this.cache.set(p,c={});return c[n]??(c[n]=this.g.getUniformLocation(p,n))}
 begin(camera,hero,time,hurt=0,lamp=[0,-1000,0],fade=0){let g=this.g;g.useProgram(this.post);g.uniform1f(this.loc(this.post,'fade'),fade);this.lamp=lamp;this.camera=camera;this.hero=hero;this.time=time;this.hurt=hurt;for(let m of this.meshes)m.data.length=0}
 shape(type,p,s,c,emit=0,rot=0){let C=Math.cos(rot),S=Math.sin(rot);this.meshes[type].data.push(C*s[0],S*s[0],0,0,-S*s[1],C*s[1],0,0,0,0,s[2],0,...p,1,...c,this.actorFade?-10-this.actorFade:emit)}
 ball(x,y,z,sx,sy,sz,c,e=0,r=0){this.shape(0,[x,y,z],[sx,sy,sz],c,e,r)}
 glow(x,y,z,sx,sy,c){this.shape(3,[x,y,z],[sx*1.3,sy*1.3,1],c,-6)}
 box(x,y,z,sx,sy,sz,c,e=0,r=0){this.shape(2,[x,y,z],[sx,sy,sz],c,e,r)}
 branch(a,b,r,c,e=0){let y=b.map((v,i)=>v-a[i]),h=Math.hypot(...y);y=norm(y);let x=norm(cross(Math.abs(y[2])<.9?[0,0,1]:[1,0,0],y)),z=cross(x,y);this.meshes[1].data.push(...x.map(v=>v*r),0,...y.map(v=>v*h),0,...z.map(v=>v*r),0,...a,1,...c,e)}
 bindTarget(t){let g=this.g;g.bindFramebuffer(g.FRAMEBUFFER,t?.fb||null);g.viewport(0,0,t?.w||this.canvas.width,t?.h||this.canvas.height)}
 draw(p,vp,light,glow=false){let g=this.g;g.useProgram(p);g.uniformMatrix4fv(this.loc(p,'vp'),false,vp);g.uniformMatrix4fv(this.loc(p,'light'),false,light);g.uniform1f(this.loc(p,'time'),this.time);if(p==this.program){g.uniform3fv(this.loc(p,'eye'),this.camera);g.uniform3fv(this.loc(p,'hero'),this.hero);g.uniform3fv(this.loc(p,'lamp'),this.lamp);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.shadowTex);g.uniform1i(this.loc(p,'depth'),0)}for(let [i,m]of this.meshes.entries())if((i===3)===glow){g.bindVertexArray(m.vao);g.drawArraysInstanced(g.TRIANGLES,0,m.count,m.data.length/20)}}
 end(){const g=this.g,e=this.camera,target=[e[0],e[1]-2.4,0],f=1/Math.tan(.56/2),a=this.canvas.width/this.canvas.height,pr=[f/a,0,0,0,0,f,0,0,0,0,-101/99,-1,0,0,-200/99,0];this.vp=mul(pr,look(e,target));let light=mul([1/18,0,0,0,0,1/18,0,0,0,0,-2/70,0,0,0,-1,1],look([e[0]-12,22,16],[e[0],0,0]));for(let m of this.meshes){g.bindBuffer(g.ARRAY_BUFFER,m.inst);g.bufferData(g.ARRAY_BUFFER,new Float32Array(m.data),g.DYNAMIC_DRAW)}g.disable(g.BLEND);g.enable(g.DEPTH_TEST);g.bindFramebuffer(g.FRAMEBUFFER,this.shadowFB);g.viewport(0,0,1024,1024);g.clear(g.DEPTH_BUFFER_BIT);this.draw(this.shadowProgram,light,light);this.bindTarget(this.scene);g.clearColor(.015,.04,.065,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.disable(g.DEPTH_TEST);g.bindVertexArray(this.empty);g.useProgram(this.sky);g.uniform1f(this.loc(this.sky,'time'),this.time);g.uniform2f(this.loc(this.sky,'shift'),e[0]*.004,a);g.drawArrays(g.TRIANGLES,0,3);g.enable(g.DEPTH_TEST);this.draw(this.program,this.vp,light);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE);g.depthMask(false);g.disable(g.DEPTH_TEST);this.draw(this.program,this.vp,light,true);g.depthMask(true);g.disable(g.BLEND);g.bindVertexArray(this.empty);g.useProgram(this.blur);for(let i=0;i<6;i++){let t=this.blooms[i%2],s=i<2?1:2;this.bindTarget(t);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,i?this.blooms[(i+1)%2].tex:this.scene.tex);g.uniform1i(this.loc(this.blur,'tex'),0);g.uniform2f(this.loc(this.blur,'step'),i%2?0:s/t.w,i%2?s/t.h:0);g.uniform1f(this.loc(this.blur,'cut'),i?0:.5);g.drawArrays(g.TRIANGLES,0,3)}this.bindTarget(null);g.useProgram(this.post);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.scene.tex);g.uniform1i(this.loc(this.post,'tex'),0);g.activeTexture(g.TEXTURE1);g.bindTexture(g.TEXTURE_2D,this.blooms[1].tex);g.uniform1i(this.loc(this.post,'bloom'),1);g.uniform1f(this.loc(this.post,'hurt'),this.hurt);g.drawArrays(g.TRIANGLES,0,3)}
}
