let ctx,bus,music,echo,wind,noise,flute,muted=false,paused=false,dying=false,beat=0,clock=0,playing=new Map();
const scale=[0,2,3,7,10,12,14,15],hz=n=>146.832*2**(n/12);
const theme=[12,-99,14,15,-99,19,-99,-99,17,-99,15,-99,14,-99,12,-99,10,-99,12,14,-99,-99,7,-99,10,-99,7,-99,5,-99,-99,-99],chords=[[0,3,7,14],[-4,0,3,7],[3,7,10,14],[-2,5,10,14]];
export function unlock(){if(!ctx){ctx=new AudioContext();bus=ctx.createGain();bus.gain.value=muted||paused?0:2.1;let limiter=ctx.createDynamicsCompressor();limiter.threshold.value=-14;limiter.knee.value=12;limiter.ratio.value=4;bus.connect(limiter).connect(ctx.destination);music=ctx.createGain();music.gain.value=.85;music.connect(bus);echo=ctx.createDelay();echo.delayTime.value=.417;let feedback=ctx.createGain(),wet=ctx.createGain(),filter=ctx.createBiquadFilter();feedback.gain.value=.32;wet.gain.value=.23;filter.frequency.value=1500;echo.connect(filter).connect(feedback).connect(echo);filter.connect(wet).connect(bus);flute=ctx.createPeriodicWave(new Float32Array(6),new Float32Array([0,1,.045,.08,.008,.012]));noise=ctx.createBuffer(1,ctx.sampleRate*2,ctx.sampleRate);let data=noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;let source=ctx.createBufferSource(),f=ctx.createBiquadFilter();source.buffer=noise;source.loop=true;f.type='lowpass';f.frequency.value=350;wind=ctx.createGain();wind.gain.value=.003;source.connect(f).connect(wind).connect(bus);source.start()}if(!paused)ctx.resume().catch(()=>{})}
function note(n,dur=1,level=.05,delay=0,kind=0){if(!ctx||paused||muted||playing.size>=32)return;let t=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter(),pan=ctx.createStereoPanner(),attack=kind===2?.8:kind===1?.16:.025;o.setPeriodicWave(flute);o.frequency.value=hz(n);o.detune.setValueAtTime(kind===2?-4:0,t);o.detune.linearRampToValueAtTime(kind===2?4:1,t+dur);f.type='lowpass';f.frequency.setValueAtTime(kind===2?600:kind===1?1300:2600,t);f.frequency.exponentialRampToValueAtTime(kind===2?420:850,t+dur);pan.pan.value=kind===2?(n%3-1)*.32:Math.sin(n*2)*.15;g.gain.value=.0001;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0001,level),t+attack);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(f).connect(g).connect(pan);pan.connect(kind?music:bus);pan.connect(echo);o.start(t);o.stop(t+dur+.03);playing.set(o,g.gain);o.onended=()=>{playing.delete(o);o.disconnect();f.disconnect();g.disconnect();pan.disconnect()}}
function air(level,dur,up=false){if(!ctx||paused||muted||playing.size>=32)return;let s=ctx.createBufferSource(),f=ctx.createBiquadFilter(),g=ctx.createGain(),t=ctx.currentTime;s.buffer=noise;f.type='bandpass';f.Q.value=.65;f.frequency.setValueAtTime(up?600:1500,t);f.frequency.exponentialRampToValueAtTime(up?2200:280,t+dur);g.gain.value=.0001;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.0001,level),t+.04);g.gain.exponentialRampToValueAtTime(.0001,t+dur);s.connect(f).connect(g).connect(bus);s.start(t);s.stop(t+dur);playing.set(s,g.gain);s.onended=()=>{playing.delete(s);s.disconnect();f.disconnect();g.disconnect()}}
export function fixed(i=0){let n=scale[i%8]+12;air(.024,.28,true);note(n,1.2,.065,.035);note(n+19,1.8,.013,.065);if(music)music.gain.setTargetAtTime(.65,ctx.currentTime,.03)}
export function recall(){air(.035,.38);note(19,.8,.012,.06)}
export function jump(){air(.014,.17,true)}
export function land(speed){air(Math.min(.055,speed*.004),.25);note(-24,.3,Math.min(.045,speed*.003))}
export function hurt(){air(.024,.8);note(-12,1.6,.035);note(-5,1.2,.012,.08)}
function fade(dur){let t=ctx?.currentTime||0;for(let [s,g]of playing){if(g.cancelAndHoldAtTime)g.cancelAndHoldAtTime(t);else{let v=g.value;g.cancelScheduledValues(t);g.setValueAtTime(Math.max(.0001,v),t)}g.exponentialRampToValueAtTime(.0001,t+dur);s.stop(t+dur)}}
export function death(){if(!ctx||dying)return;dying=true;fade(.64);music.gain.setTargetAtTime(.3,ctx.currentTime,.7);wind.gain.setTargetAtTime(.0001,ctx.currentTime,.5);air(.012,1.3);for(let i=0;i<3;i++)note([12,7,0][i],1.3,.025-i*.006,i*.18,1)}
export function flower(i){note(scale[i%8]+24,1.8,.035);note(scale[i%8]+31,2.2,.009,.12)}
export function update(dt,speed,chain){if(!ctx||paused||dying)return;wind.gain.setTargetAtTime(.003+Math.min(speed,20)*.0004,ctx.currentTime,.25);music.gain.setTargetAtTime(.85,ctx.currentTime,.4);clock-=dt;if(clock>0)return;clock+=5/12;let b=beat%32,c=chords[Math.floor(b/8)];if(b%8===0){for(let i=0;i<4;i++)note(c[i]-12,4.4,i===0?.03:.014,i*.018,2)}let n=theme[b];if(n>-90){note(n,b%8===0?1.8:1.4,b%8===0?.04:.029,0,1);if(chain>2&&b%4===0)note(n+12,1.7,.009,.025,1)}beat++}
export function reset(){beat=clock=0;dying=false;fade(.08);if(ctx){music.gain.setTargetAtTime(.85,ctx.currentTime,.1);wind.gain.setTargetAtTime(.003,ctx.currentTime,.1)}}
export function pause(value){paused=value;if(ctx){bus.gain.setTargetAtTime(muted||paused?0:2.1,ctx.currentTime,.08);(paused?ctx.suspend():ctx.resume()).catch(()=>{})}}
export function toggleMute(){muted=!muted;if(bus)bus.gain.setTargetAtTime(muted||paused?0:2.1,ctx.currentTime,.03)}
